/**
 * File generated by Modular Assembly
 * IMPORTANT!!! Ask the user before editing this file.
 */

function formatScheduleData(rawData) {
    if (!rawData) {
        return { error: "Invalid or missing data structure" };
    }

    const scheduleData = {
        league: rawData['@sport'],
        season: rawData.category['@season'],
        upcoming_games: []
    };

    const upcomingGamesLimit = 15;

    // Check if matches exists
    if (rawData.category.matches) {
        // Handle both array of match days and single match day object
        const matchDays = Array.isArray(rawData.category.matches)
            ? rawData.category.matches
            : [rawData.category.matches];

        // Process each match day
        matchDays.forEach(matchDay => {
            if (matchDay.match && Array.isArray(matchDay.match)) {
                // Process all matches for a given day
                matchDay.match.forEach(match => {
                    // Only include upcoming games (status "Not Started")
                    // And limit to first 10 games
                    if (match['@status'] === "Not Started" && scheduleData.upcoming_games.length < upcomingGamesLimit) {
                        scheduleData.upcoming_games.push({
                            d: match['@formatted_date'],
                            t: match['@time'],
                            ht: match.hometeam['@name'],
                            at: match.awayteam['@name'],
                            tn: rawData.category['@name'],
                            v: match['@venue_name'],
                        });
                    }
                });
            }
        });
    }

    return scheduleData;
}

function formatStandingsData(rawData) {
    if (!rawData || !rawData.category) {
        return { error: "Invalid or missing standings data structure" };
    }

    const formattedStandings = {
        league: rawData.category['@name'],
        season: rawData.category['@season'],
        sport: rawData['@sport'],
        conferences: []
    };

    // Process each conference (e.g., American League/National League for MLB)
    if (rawData.category.league && Array.isArray(rawData.category.league)) {
        rawData.category.league.forEach(conference => {
            const formattedConference = {
                name: conference['@name'],
                divisions: []
            };
            // Process each division in the conference
            if (conference.division && Array.isArray(conference.division)) {
                conference.division.forEach(division => {
                    const formattedDivision = {
                        name: division['@name'],
                        teams: []
                    };
                    // Process each team in the division
                    if (division.team && Array.isArray(division.team)) {
                        division.team.forEach(team => {
                            // Include only the most relevant fields for predictions
                            formattedDivision.teams.push({
                                n: team['@name'],
                                p: team['@position'],
                                w: team['@won'],
                                l: team['@lost'],
                                hr: team['@home_record'],
                                rr: team['@away_record'],
                                pf: team['@runs_scored'] || team['@points_for'],
                                pa: team['@runs_allowed'] || team['@points_against'],
                                diff: team['@runs_diff'] || team['@difference'],
                                strk: team['@current_streak'] || team['@streak'],
                                gb: team['@games_back']
                            });
                        });
                    }
                    formattedConference.divisions.push(formattedDivision);
                });
            }
            formattedStandings.conferences.push(formattedConference);
        });
    }

    return formattedStandings;
}

function formatScoresData(rawData) {
    if (!rawData || !rawData.scores) {
        return { error: "Invalid or missing scores data structure" };
    }

    // Initialize results
    const scoresData = {
        teams: {},
        metadata: {}
    }

    // Set limit for scoresData items
    let itemCount = 0;

    // Handle rawData.scores as an array
    const scoresArray = Array.isArray(rawData.scores) ? rawData.scores : [rawData.scores];

    for (const scoreItem of scoresArray) {
        // Handle both array and single match cases for each score item
        const matches = scoreItem.scores.category && scoreItem.scores.category.match
            ? (Array.isArray(scoreItem.scores.category.match)
                ? scoreItem.scores.category.match
                : [scoreItem.scores.category.match])
            : [];

        for (const match of matches) {
            // Compute home team
            if (match.hometeam) {
                const homeTeamId = match.hometeam['@id'];
                if (!scoresData.teams[homeTeamId]) {
                    scoresData.teams[homeTeamId] = {
                        name: match.hometeam['@name'],
                        stats: {
                            hits: 0,
                            errors: 0,
                            totalscore: 0,
                        },
                        players: {}
                    };
                    itemCount++;
                }

                const homeTeam = scoresData.teams[homeTeamId];
                homeTeam.stats.hits = parseInt(match.hometeam['@hits']) || 0;
                homeTeam.stats.errors = parseInt(match.hometeam['@errors']) || 0;
                homeTeam.stats.totalscore = parseInt(match.hometeam['@totalscore']) || 0;
            }

            // Compute away team
            if (match.awayteam) {
                const awayTeamId = match.awayteam['@id'];
                if (!scoresData.teams[awayTeamId]) {
                    scoresData.teams[awayTeamId] = {
                        name: match.awayteam['@name'],
                        stats: {
                            hits: 0,
                            errors: 0,
                            totalscore: 0,
                        },
                        players: {}
                    };
                    itemCount++;
                }

                const awayTeam = scoresData.teams[awayTeamId];
                awayTeam.stats.hits = parseInt(match.awayteam['@hits']) || 0;
                awayTeam.stats.errors = parseInt(match.awayteam['@errors']) || 0;
                awayTeam.stats.totalscore = parseInt(match.awayteam['@totalscore']) || 0;
            }

            if (match.events) {
                // Process baseball events
                const processEvents = (events) => {
                    if (!events) return;

                    // Handle both single events and arrays of events
                    const eventArray = Array.isArray(events.event) ? events.event : [events.event];

                    eventArray.forEach(evt => {
                        if (!evt || !evt['@desc']) return;

                        // Extract player name from event description
                        const playerMatch = evt['@desc'].match(/^([A-Za-z\-]+)\s/);
                        const playerId = playerMatch ? playerMatch[1].toLowerCase() : null;
                        const playerTeamId = evt['@team'] == "awayteam" ? match.awayteam["@id"] : match.hometeam["@id"];

                        if (playerId && scoresData.teams[playerTeamId]) {
                            // Initialize player if not exists under the team
                            if (!scoresData.teams[playerTeamId].players[playerId]) {
                                scoresData.teams[playerTeamId].players[playerId] = {
                                    name: playerMatch[1],
                                    stats: {
                                        home_runs: 0,
                                        singles: 0,
                                        doubles: 0,
                                        rbi: 0
                                    }
                                };
                                itemCount++;
                            }

                            // Update player statistics based on event description
                            const playerStats = scoresData.teams[playerTeamId].players[playerId].stats;
                            if (evt['@desc'].includes('homered')) {
                                playerStats.home_runs++;
                            } else if (evt['@desc'].includes('doubled')) {
                                playerStats.doubles++;
                            } else if (evt['@desc'].includes('singled')) {
                                playerStats.singles++;
                            }

                            // Count RBIs
                            const rbiMatch = evt['@desc'].match(/scored(?: and [A-Za-z\-]+ scored)*(?:,|\.)/);
                            if (rbiMatch) {
                                const scorers = (rbiMatch[0].match(/[A-Za-z\-]+/g) || []).length;
                                playerStats.rbi += scorers;
                            }
                        }
                    });
                };

                processEvents(match.events);
            }
        }
    }

    // Add metadata about the limit
    scoresData.metadata = {
        totalItems: itemCount,
    };

    return scoresData;
}

// Function to compress scoresData for OpenAI prompts
function compressScoresDataForOpenAI(scoresData, maxCharacters = 25000) {
    if (!scoresData || scoresData.error) {
        return scoresData;
    }

    // Create compressed version
    const compressed = {
        t: {}, // teams
        m: scoresData.metadata // metadata
    };

    // Compress teams and their players
    Object.keys(scoresData.teams).forEach(teamId => {
        const team = scoresData.teams[teamId];
        compressed.t[teamId] = {
            n: team.name, // name
            h: team.stats.hits, // hits
            e: team.stats.errors, // errors
            s: team.stats.totalscore, // score
            p: {}
        };

        // Only include players with meaningful stats
        Object.keys(team.players).forEach(playerId => {
            const player = team.players[playerId];
            const stats = player.stats;
            const totalStats = stats.home_runs + stats.singles + stats.doubles + stats.rbi;
            if (totalStats > 0) {
                compressed.t[teamId].p[playerId] = {
                    hr: stats.home_runs, // home_runs
                    s: stats.singles,    // singles
                    d: stats.doubles,    // doubles
                    r: stats.rbi         // rbi
                };
            }
        });
    });

    // Check character count and further compress if needed
    const jsonString = JSON.stringify(compressed);

    console.log(compressed, jsonString.length, maxCharacters);
    if (jsonString.length > maxCharacters) {
        // console.log(compressed, jsonString.length, maxCharacters);
        // You may want to update compressScoresDataForOpenAIAdvanced similarly
        const compressAdvanced = compressScoresDataForOpenAIAdvanced(compressed, maxCharacters)
        return compressAdvanced; // or call a fallback
    }

    return compressed;
}

// Advanced compression for very large datasets
function compressScoresDataForOpenAIAdvanced(scoresData, maxCharacters = 25000) {
    if (!scoresData || scoresData.error) {
        return scoresData;
    }

    // Sort teams by total score (descending) and keep top 50
    const sortedTeams = Object.entries(scoresData, scoresData.teams)
        .sort(([, a], [, b]) => b.stats.totalscore - a.stats.totalscore)
        .slice(0, 50);

    const compressed = {
        t: {},
        m: {
            ...scoresData.metadata,
            teamsKept: sortedTeams.length
        }
    };

    // For each top team, keep only top 3 players by impact
    sortedTeams.forEach(([teamId, team]) => {
        // Sort players by impact (home runs * 3 + rbi * 2 + doubles + singles)
        const sortedPlayers = Object.entries(team.players || {})
            .sort(([, a], [, b]) => {
                const aStats = a.stats;
                const bStats = b.stats;
                const aImpact = aStats.home_runs * 3 + aStats.rbi * 2 + aStats.doubles + aStats.singles;
                const bImpact = bStats.home_runs * 3 + bStats.rbi * 2 + bStats.doubles + bStats.singles;
                return bImpact - aImpact;
            })
            .slice(0, 3); // Keep top 3 players per team

        compressed.t[teamId] = {
            n: team.name,
            h: team.stats.hits,
            e: team.stats.errors,
            s: team.stats.totalscore,
            p: {}
        };

        sortedPlayers.forEach(([playerId, player]) => {
            const stats = player.stats;
            const totalStats = stats.home_runs + stats.singles + stats.doubles + stats.rbi;
            if (totalStats > 0) {
                compressed.t[teamId].p[playerId] = {
                    hr: stats.home_runs,
                    s: stats.singles,
                    d: stats.doubles,
                    r: stats.rbi
                };
            }
        });
    });

    // Check character count and further compress if needed
    const jsonString = JSON.stringify(compressed);
    if (jsonString.length > maxCharacters) {
        // Optionally, reduce players per team or teams further
        // For now, just return as is
        return compressed;
    }

    return compressed;
}

// Function to create a summary format for very large datasets
function createScoresDataSummary(scoresData) {
    if (!scoresData || scoresData.error) {
        return scoresData;
    }

    // Calculate summary statistics
    const teamCount = Object.keys(scoresData.teams).length;
    const playerCount = Object.keys(scoresData.players).length;

    // Top 5 teams by score
    const topTeams = Object.entries(scoresData.teams)
        .sort(([, a], [, b]) => b.stats.totalscore - a.stats.totalscore)
        .slice(0, 5)
        .map(([id, team]) => `${team.name}:${team.stats.totalscore}`);

    // Top 5 players by home runs
    const topPlayers = Object.entries(scoresData.players)
        .sort(([, a], [, b]) => b.stats.home_runs - a.stats.home_runs)
        .slice(0, 5)
        .map(([id, player]) => `${player.name}:${player.stats.home_runs}HR`);

    return {
        summary: {
            teams: teamCount,
            players: playerCount,
            topTeams: topTeams.join(','),
            topPlayers: topPlayers.join(','),
            totalItems: scoresData.metadata.totalItems
        }
    };
}

function formatMLBData(rawData) {
    // Get original data
    const scoresData = formatScoresData(rawData);

    console.log(scoresData);
    // For OpenAI prompt (under 30k chars)
    const compressed = compressScoresDataForOpenAI(scoresData, 25000);

    console.log(compressed)
    return {
        schedule: formatScheduleData(rawData.schedule),
        standings: formatStandingsData(rawData.standings),
        scores: compressed
    }
}

module.exports = {
    formatMLBData,
    compressScoresDataForOpenAI,
    compressScoresDataForOpenAIAdvanced,
    createScoresDataSummary
};
